import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const leagueSpartan = localFont({
  src: "./fonts/LeagueSpartan-VariableFont_wght.ttf",
  variable: "--font-league-spartan",
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={leagueSpartan.variable}>
      <head>
        <link 
          rel="preload" 
          href="/fonts/LeagueSpartan-VariableFont_wght.ttf" 
          as="font" 
          type="font/ttf" 
          crossOrigin="anonymous" 
        />
        <style dangerouslySetInnerHTML={{ __html: `
          :root {
            --font-league-spartan: 'League Spartan', sans-serif;
            --default-font-family: 'League Spartan', sans-serif !important;
          }
          
          html, body, * {
            font-family: 'League Spartan', var(--font-league-spartan), sans-serif !important;
          }
        `}} />
      </head>
      <body
        className="antialiased font-sans"
        style={{ fontFamily: "'League Spartan', var(--font-league-spartan), sans-serif" }}
      >
        {children}
      </body>
    </html>
  );
}
